---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
  - name: bosh-src

run:
  path: bosh-src/ci/tasks/test-unit.sh

params:
  RUBY_VERSION: replace-me
  DB:           replace-me
  DB_VERSION:   replace-me
  DB_HOST:      localhost
  DB_USER:      rds-only
  DB_PASSWORD:  rds-only
